import { TablesType } from '@/types/types';

export const Mesas: TablesType[] = [
	{
		id: 1,
		mesaNome: 'Mesa 1',
		status: 'ocupada',
		guests: 4,
		time: '14:30',
		server: 'João Silva',
		clienteNome: 'Marina Rocha Silva',
		products: [],
	},
	{ id: 2, mesaNome: 'Mesa 2', clienteNome: 'Livre', status: 'livre', guests: 0, time: '', server: '', products: [] },
	{
		id: 3,
		mesaNome: 'Mesa 3',
		clienteNome: 'Laura Almeida Rodrigues',
		status: 'reservada',
		guests: 2,
		time: '15:00',
		server: 'Maria Oliveira',
		products: [],
	},
	{
		id: 4,
		mesaNome: 'Mesa 4',
		status: 'ocupada',
		guests: 3,
		time: '13:45',
		server: 'Carlos Santos',
		clienteNome: 'Raissa Castro Fernandes',
		products: [],
	},
	{ id: 5, mesaNome: 'Mesa 5', status: 'livre', guests: 0, time: '', server: '', clienteNome: 'Livre', products: [] },
	{
		id: 6,
		mesaNome: 'Mesa 6',
		status: 'ocupada',
		guests: 6,
		time: '14:15',
		server: 'Ana Pereira',
		clienteNome: 'Caio Melo Ferreira',
		products: [],
	},
	{
		id: 7,
		mesaNome: 'Mesa 7',
		status: 'livre',
		guests: 0,
		time: '',
		server: '',
		clienteNome: 'Livre',
		products: [],
	},
	{ id: 8, mesaNome: 'Mesa 8', status: 'livre', guests: 0, time: '', server: '', clienteNome: 'Livre', products: [] },
	{ id: 9, mesaNome: 'Mesa 9', status: 'livre', guests: 0, time: '', server: '', clienteNome: 'Livre', products: [] },
];
